fun main(){
    println("Enter Student Enrollment no:")
    val eno = readLine()
    println("Enter Student Name:")
    val name = readLine()
    println("Enter Branch:")
    val branch = readLine()
    println("Enter Class:")
    val classname = readLine()
    println("Enter Batch:")
    val batch = readLine()
    println("Enter CollegeName:")
    val college = readLine()
    println("Enter University:")
    val uni = readLine()
    println("Enter Age:")
    val age = readLine()
    println()
    println("**********************")
    println()
    println("Student Information")
    println("Student Enrollment no: $eno")
    println("Student Name: $name")
    println("Student Branch: $branch")
    println("Student Class: $classname")
    println("Student Batch: $batch")
    println("Student College: $college")
    println("Student University: $uni")
    println("Student Age: $age")
}